'use client';

import { useState } from 'react';

const navItems = [['01','ECOSYSTEM'],['02','LIQUIDITY_POOLS'],['03','LUMEN_INDEX'],['04','GOVERNANCE']];
const verticals = ['12.6%','37.5%','61.9%','86.2%'];
const horizontals = ['32.7%','71.4%'];
const Wallet=()=> <span className="wallet" aria-hidden="true" />;
const PrimeChip=()=> <span className="prime-chip">PRIME_MEMBER</span>;

function Grid(){return <div className="grid-art" aria-hidden="true">{verticals.map((left,i)=><i className="grid-v anim-grid-v" key={left} style={{left,animationDelay:`${600+i*100}ms`}}/>)}{horizontals.map((top,i)=><i className="grid-h anim-grid-h" key={top} style={{top,animationDelay:`${800+i*150}ms`}}/>)}{horizontals.flatMap((top,hi)=>verticals.map((left,vi)=><b className="plus anim-scale-in" key={`${top}-${left}`} style={{top,left,animationDelay:`${1000+(hi*4+vi)*80}ms`}}/>))}</div>}
function Nodes(){const lines=[['38%','14%','52%','14%',1200],['52%','14%','60%','27%',1400],['32%','58%','20%','74%',1500],['20%','74%','6%','74%',1700],['78%','53%','63%','53%',1800],['63%','53%','50%','63%',2000]];return <div className="nodes" aria-hidden="true">{lines.map(([x1,y1,x2,y2,delay],i)=><svg className="connector anim-fade-in" style={{animationDelay:`${delay}ms`}} key={i}><line x1={x1} y1={y1} x2={x2} y2={y2}/></svg>)}<i className="node node-one anim-scale-in" style={{animationDelay:'1500ms'}}/><i className="node node-two anim-scale-in" style={{animationDelay:'1800ms'}}/><i className="node node-three anim-scale-in" style={{animationDelay:'2100ms'}}/><div className="node-label label-one anim-slide-left" style={{animationDelay:'1100ms'}}><span>[ CORE_ENTITY ]</span><p>Neural node processing real-time data streams.</p></div><div className="node-label label-two anim-slide-left" style={{animationDelay:'1400ms'}}><span>[ LUMINOUS_INSIGHT ]</span><p>Deep-learning engine synthesizing raw inputs.</p></div><div className="node-label label-three anim-slide-right" style={{animationDelay:'1700ms'}}><span>[ CONNECTIVITY ]</span><p>Latency-free transmission across distributed networks.</p></div></div>}
export default function Home(){const[menuOpen,setMenuOpen]=useState(false);return <section className="lumen"><video className="backdrop-video anim-fade-in" src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260813_115057_94c3699b-0fd1-4124-bcf3-3626bb8c1f77.mp4" autoPlay muted loop playsInline/><div className="content"><nav><div className="nav-left"><span className="wordmark anim-fade-up" style={{animationDelay:'200ms'}}>LŪMEN // ÍNDEX</span><div className="desktop-nav">{navItems.map(([n,l],i)=><span className="nav-item anim-fade-up" key={n} style={{animationDelay:`${350+i*100}ms`}}><em>{n}.</em><b>{l}</b></span>)}</div></div><div className="wallet-strip anim-slide-right" style={{animationDelay:'600ms'}}><Wallet/><span>0x71...f4e2</span><strong>[ CONNECTED ]</strong><span className="status">STATUS:</span><PrimeChip/></div><button className="menu-toggle anim-fade-in" style={{animationDelay:'400ms'}} onClick={()=>setMenuOpen(!menuOpen)} aria-label="Toggle menu"><span className={menuOpen?'hamburger closed':'hamburger'}>☰</span><span className={menuOpen?'close-icon visible':'close-icon'}>×</span></button></nav><div className={`mobile-menu ${menuOpen?'open':''}`}><button className="menu-backdrop" aria-label="Close menu" onClick={()=>setMenuOpen(false)}/><div className="menu-panel"><button className="menu-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu">×</button><div className="menu-links">{navItems.map(([n,l],i)=><button key={n} onClick={()=>setMenuOpen(false)} style={{transitionDelay:menuOpen?`${150+i*75}ms`:'0ms'}}><em>{n}.</em>{l}</button>)}</div><div className="mobile-wallet"><div><Wallet/><span>0x71...f4e2</span><strong>[ CONNECTED ]</strong></div><div><span>STATUS:</span><PrimeChip/></div></div></div></div><h1 className="anim-fade-up" style={{animationDelay:'400ms'}}>Liquid Assets.<br/>Luminous Returns.</h1><Grid/><Nodes/><div className="bottom-row"><button className="cta anim-fade-up" style={{animationDelay:'900ms'}}><i>✦</i><span>Explore Private Banking</span></button><aside className="info-card anim-slide-right" style={{animationDelay:'1100ms'}}><span className="ecosystem-badge">NOT A BANK — AN ECOSYSTEM</span><div className="card-body"><svg viewBox="0 0 280 168" preserveAspectRatio="none"><polygon points="0.5,0.5 279.5,0.5 279.5,167.5 30,167.5 0.5,137.5"/></svg><p>Maps the complexity of modern finance with a partner that brings clarity and organic growth to your portfolio.</p><a>VIEW_TRANSPARENCY_REPORT</a></div></aside></div></div></section>}
